# Uses defaults from https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# which is based on this ruby style guide https://github.com/bbatsov/ruby-style-guide

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'lib/tasks/import_words.rake'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
