# Uses defaults from https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# which is based on this ruby style guide https://github.com/bbatsov/ruby-style-guide

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
